#!/bin/bash


## Make user group and directories
##
groupadd mqm
useradd mqm -g mqm
# Allow mqm to sudo
echo 'mqm ALL=(ALL)       NOPASSWD:ALL' >> /etc/sudoers
# add new MQ bin's to the path (won't be there until the install is donw)
echo 'PATH="$PATH:/opt/mqm92/bin"' >> ~mqm/.bashrc
echo 'export PATH' >> ~mqm/.bashrc
# make the directories
mkdir /var/mqm92
mkdir /opt/mqm92
mkdir /opt/software/IBM_MQ -p


## Expand the installation file in the software directory
##
#  (assumes you have already got the file on the server and you are inthe same dir)
mv IBM_MQ_9.2.0.2_LINUX_X86-64.tar.gz /opt/software/IBM_MQ/
cd /opt/software/IBM_MQ/
tar xvf IBM_MQ_9.2.0.2_LINUX_X86-64.tar.gz
chown -R mqm:mqm /var/mqm92 /opt/mqm92 /opt/software/IBM_MQ


## Install the software
##
cd MQServer/
# Accept the license
./mqlicense.sh << @
1
@

# package used be crtmqpkg
yum install-y rpm-build createrepo

#add installation92 suffix to rpm files and makes /opt/mqm92 as installation dir
./crtmqpkg installation92 /opt/mqm92
cd /var/tmp/mq_rpms/installation92/x86_64
# install MQ packages (can just do rpm -ivh MQ* to install the lot)
rpm -ivh MQSeriesServer_installation92-9.2.0-2.x86_64.rpm MQSeriesWeb_installation92-9.2.0-2.x86_64.rpm MQSeriesSamples_installation92-9.2.0-2.x86_64.rpm MQSeriesSDK_installation92-9.2.0-2.x86_64.rpm MQSeriesRuntime_installation92-9.2.0-2.x86_64.rpm MQSeriesMan_installation92-9.2.0-2.x86_64.rpm MQSeriesJRE_installation92-9.2.0-2.x86_64.rpm MQSeriesJava_installation92-9.2.0-2.x86_64.rpm MQSeriesGSKit_installation92-9.2.0-2.x86_64.rpm MQSeriesExplorer_installation92-9.2.0-2.x86_64.rpm 

## set up web users (optional this is not scripted)
#cp /opt/mqm92/web/mq/samp/configuration/basic_registry.xml /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
# Add userrmqwebadmin and add to group.
#
#vi /opt/mqm92/web/mq/etc/mqweb.xml 
#change httpHost from localhost to *
#
#su - mqm
#/opt/mqm92/bin/strmqweb 
#( To stop the web server use /opt/mqm92/bin/endmqweb )
#
#https://<server>:9443/ibmmq/console    (NOTE: doesn't work in Chrome)

dspmq
ps -ef | grep mqm

##### Ready to make DMGR's

:wq


crtmqm -u SYSTEM.DEAD.LETTER.QUEUE -p 1418 QMTRY03
dspmq
strmqm QMTRY03
dspmq

DISPLAY QMGR
DISPLAY QUEUE(SYSTEM*)

DEFINE QLOCAL(QL.A) REPLACE DESCR('QL.A QUEUE')
DISPLAY QLOCAL(QL.A)
ALTER QLOCAL(QL.A) MAXDEPTH(1000)
DISPLAY QLOCAL(QL.A)


[Repeat for QL.B]
DEFINE QLOCAL(QL.B) REPLACE DESCR('QL.B QUEUE')
DEFINE QLOCAL(QL.B) REPLACE MAXDEPTH(2000)    looses the DESC
DEFINE QLOCAL(QL.B) REPLACE MAXDEPTH(2000) DESCR('QL.B QUEUE')   got both

(So DEFINE overwrites exisitng Q setting

##Using a script:
created script.mqsc:

DISPLAY QMGR
DISPLAY QUEUE(SYSTEM*)
DEFINE QLOCAL(QL.A) REPLACE DESCR('QL.A QUEUE')
DISPLAY QLOCAL(QL.A)
ALTER QLOCAL(QL.A) MAXDEPTH(1000)
DEFINE QLOCAL(QL.B) REPLACE DESCR('QL.B QUEUE')
DEFINE QLOCAL(QL.B) REPLACE MAXDEPTH(2000) DESCR('QL.B QUEUE')
DISPLAY QLOCAL(QL.B)







new QMGR

crtmqm -u SYSTEM.DEAD.LETTER.QUEUE -p 1419 QMTRY04
strmqm QMTRY04
dspmq
runmqsc < script.mqsc > script.report
cat script.report

endmqm
-c controlled (wait for all connectios to finish)
-w (as above but print report on status periodically)
-i immediate (closes connections etc)
-p preemptive (doesn't wait for calls just drops dangerous so use as last resort)
last -  kill the qmgr process


Q alias
DEFINE QALIAS(QA.A) TARGET(QL.A)
DEFINE QALIAS(QA.B) TARGET(QL.B)

 ./amqsput QA.A QMTRY04
msg
msg
^D

 ./amqsget QA.A QMTRY04



#################### distrib q
crtmqm -p 1420 QMSND01
crtmqm -p 1421 QMRCV01

runmqsc QMSND01

DEFINE QREMOTE(QNDF.1)
ALTER QREMOTE(QNDF.1) RNAME(QNDF.1) RQMNAME(QMRCV01)
DEFINE QLOCAL(SND.TO.RCV) REPLACE USAGE(XMITQ)
ALTER QREMOTE(QNDF.1) XMITQ(SND.TO.RCV)
DISPLAY QREMOTE(QNDF.1)
DEFINE CHANNEL(SND.TO.RCV) CHLTYPE(SDR) CONNAME('localhost(1421)') XMITQ(SND.TO.RCV)
START CHANNEL(SND.to.rcv)
DISPLAY CHSTATUS(SND.to.rcv)
end


runmqsc QMRCV01

DEFINE QLOCAL(QNDF.1)
DEFINE CHANNEL(SND.TO.RCV) CHLTYPE(RCVR)
DISPLAY CHSTATUS(SND.TO.RCV)
STOP CHANNEL(SND.TO.RCV)
DISPLAY CHSTATUS(SND.TO.RCV)
# just for showing off troubleshooting
#STOP CHANNEL(SND.TO.RCV) MODE(FORCE)
#DISPLAY CHSTATUS(SND.TO.RCV)

/opt/mqm92/samp/bin/amqsput QNDF.1 QMSND01
msg
msg
msg
^D

find channel that XMIT Q uses
DISPLAY CHANNEL(*) CHTYPE(SDR
find the one with the XMITQ 

:wq



#Stop all the QMGRs
for q in $(dspmq | sed 's/.*(\(.*\)) .*$/\1/') ; do
  endmqm $q
done
